Authpages
grazac-academy/easy-rent-product-frontend pull request #11
Opened 2022-05-09 15:21 UTC by Eyiowuawi

this branch contains the following:
1) login, signup, new password and forgot password pages 
2) product listing page
3) bookmark context & bookmark functionality

2022-05-09 16:30 UTC, mayowadabiri requested changes
- You need to work on your naming convention
- I don't think the context you're using is needed at this point.. Context API + useReducer is used for managing complex state. 

Nice work by the way

2022-05-09 16:30 UTC, mayowadabiri commented on src/index.js
> +      <Context>
This context is used by what component?? What is work of the context?

2022-05-09 18:41 UTC, Eyiowuawi commented on src/Context/Context.jsx
> +const Bookmark = createContext();
corrected

2022-05-09 18:42 UTC, Eyiowuawi commented on src/Constant/Array.jsx
> +    Price: '10,000',
done and i have also check W3schools for more insight.. thanks sir

2022-05-09 18:42 UTC, Eyiowuawi commented on src/Context/Context.jsx
> +    apartments: Array,
this has also been changed to appartments

2022-05-09 18:43 UTC, Eyiowuawi commented on src/components/ApartmentCard/ApartmentCard.jsx
> +    console.log(bookmark);
done

2022-05-09 18:43 UTC, Eyiowuawi commented on src/components/Button/Button2.jsx
> +function Button2({ children }) {
done

2022-05-09 18:45 UTC, Eyiowuawi commented on src/components/Button/Button2.jsx
> +    <Link to='/'>
it's the button component that can take image... even tho currently the design is up for change to just contain an image (back arrow).

2022-05-09 18:49 UTC, Eyiowuawi commented on src/index.js
> +      <Context>
the context is used by the Featured apartment on the landing page, the apartment listing page and the bookmark page which might have an icon that tracks the length of bookmarked apartment array on the nav bar just like the cart length in my last project

2022-05-10 07:46 UTC, mayowadabiri requested changes

2022-05-10 07:46 UTC, mayowadabiri commented on src/components/FeaturedApartment/FeaturedApartment.js
> +import {BookmarkState} from '../../Context/Context';
Change this to small letter. `bookmarkState`. Also, change the file name to small letter

2022-05-10 07:46 UTC, mayowadabiri commented on src/index.js
> +import Context from './Context/Context';
Here also

2022-05-10 07:46 UTC, mayowadabiri commented on src/pages/Apartmentlist/Apartmentlist.jsx
> +import ApartmentCard from '../../components/ApartmentCard/ApartmentCard';
Can you check the way I am importing files now.. Check the set of files I merged, like Aisha's file.. It's imported as just `'components/ApartmentCard/ApartmentCard'` No need for those back slashes

2022-05-10 07:46 UTC, mayowadabiri commented on src/pages/ResetPassword/ResetPassword.jsx
> +import FormGroup from './../../components/FormGroup/FormGroup';
Pls work on the way you import files

2022-05-10 08:13 UTC, mayowadabiri commented on src/components/Button/Button2.jsx
> +    <Link to='/'>
Why using a and button tag together.. That's semantically not correct.
Is it leading to another page to going to perform an action?

2022-05-10 13:13 UTC, merged